# from gym_ste.envs.basic_ste_env import BasicSteEnv
from gym_ste.envs.ste_easy import SteEasyEnv
from gym_ste.envs.ste_very_easy import SteVeryEasyEnv
from gym_ste.envs.ste_hard import SteHardEnv
from gym_ste.envs.ste_very_hard import SteVeryHardEnv
from gym_ste.envs.ste_without_pose import SteWithoutPoseEnv

#from gym_ste.envs.ste_pf_modified import StePFilterModEnv
from gym_ste.envs.ste_pf_easy import StePFilterEasyEnv
from gym_ste.envs.ste_pf_hard import StePFilterHardEnv
from gym_ste.envs.ste_pf_very_hard import StePFilterVeryHardEnv
from gym_ste.envs.ste_pf_converge_easy import StePFilterConvEasyEnv
from gym_ste.envs.ste_pf_converge_hard import StePFilterConvHardEnv
from gym_ste.envs.ste_pf_converge_very_hard import StePFilterConvVeryHardEnv

from gym_ste.envs.ste_pf_relative_converge_hard import StePFilterRelativeConvHardEnv
from gym_ste.envs.ste_pf_relative_converge_very_hard import StePFilterRelativeConvVeryHardEnv


from gym_ste.envs.ste_pf_converge_center_hard import StePFilterConvCenterHardEnv
from gym_ste.envs.ste_pf_converge_center_very_hard import StePFilterConvCenterVeryHardEnv
from gym_ste.envs.ste_pf_converge_center_extreme import StePFilterConvCenterExtremeEnv
from gym_ste.envs.ste_pf_converge_center_extreme_mat import StePFilterConvCenterExtremeMatEnv


from gym_ste.envs.ste_pf_vel_converge_center_extreme import StePFilterVelConvCenterExtremeEnv
from gym_ste.envs.ste_pf_vel_converge_center_extreme_mat import StePFilterVelConvCenterExtremeMatEnv

from gym_ste.envs.ste_pf_vel_converge_center_very_hard import StePFilterVelConvCenterVeryHardEnv


from gym_ste.envs.ste_pf_veiled_vel_converge_center_extreme import StePFilterVeiledVelConvCenterExtremeEnv


from gym_ste.envs.ste_est_vel_extreme import SteEstVelExtremeEnv


from gym_ste.envs.ste_pf_relative_converge_center_very_hard import StePFilterRelativeConvCenterVeryHardEnv


from gym_ste.envs.ste_pf_converge_infotaxis_extreme_mat import StePFilterConvInfotaxisExtremeMatEnv
from gym_ste.envs.ste_pf_converge_infotaxis_extreme import StePFilterConvInfotaxisExtremeEnv
from gym_ste.envs.ste_pf_converge_infotaxis_very_hard import StePFilterConvInfotaxisVeryHardEnv
from gym_ste.envs.ste_pf_converge_infotaxis_hard import StePFilterConvInfotaxisHardEnv


#from gym_ste.envs.ste_pf_easy2 import StePFilterEasyEnv2
#from gym_ste.envs.ste_pf_converge_hard_2 import StePFilterConvHardEnv2
#from gym_ste.envs.ste_pf_converge_hard_3 import StePFilterConvHardEnv3
#from gym_ste.envs.ste_pf_hard_2 import StePFilterHardEnv2

from gym_ste.envs.ste_est_hard import SteEstHardEnv

#from gym_ste.envs.ste_negative_hard import SteNegativeHardEnv

# from gym_ste.envs.ste_easy import SteEasy
